# Generated by Django 5.2 on 2025-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneurship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_image', models.ImageField(upload_to='workeshop_images/')),
                ('course_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
