# Generated by Django 5.2 on 2025-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0002_entrepreneurship'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurship',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
