# Generated by Django 5.2 on 2025-05-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0003_entrepreneurship_published_newsletter_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider_images/')),
                ('slider_title', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='hero_image',
        ),
    ]
