# Generated by Django 5.2.1 on 2025-05-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0004_slider_remove_newsletter_hero_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='News',
        ),
    ]
