# Generated by Django 5.2.1 on 2025-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0005_rename_newsletter_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_image', models.ImageField(upload_to='workeshop_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='entrepreneurship',
            name='workshop_image',
        ),
        migrations.AddField(
            model_name='entrepreneurship',
            name='course_image',
            field=models.ImageField(default=1, upload_to='course_images/'),
            preserve_default=False,
        ),
    ]
