# Generated by Django 5.2.1 on 2025-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0006_workshop_remove_entrepreneurship_workshop_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
