# Generated by Django 5.2.1 on 2025-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0007_workshop_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurship',
            name='course_lab',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
