# Generated by Django 5.2.1 on 2025-05-28 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0008_entrepreneurship_course_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurship',
            name='course_lab',
            field=models.CharField(blank=True, choices=[('Innovative Manufacturing', 'Innovative Manufacturing'), ('Smart Factory Center', 'Smart Factory Center'), ('AR | VR | MR Research Centre', 'AR | VR | MR Research Centre'), ('Research Centre For PLM', 'Research Centre For PLM'), ('Research Centre For Asset Performance', 'Research Centre For Asset Performance'), ('Product Innovation Center', 'Product Innovation Center'), ('Predictive Engineering', 'Predictive Engineering')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('college_or_organization', models.CharField(max_length=255)),
                ('department_or_domain', models.CharField(max_length=255)),
                ('year_or_experience', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tansam_apl.entrepreneurship')),
            ],
        ),
    ]
