# Generated by Django 5.2.1 on 2025-05-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0009_alter_entrepreneurship_course_lab_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurship',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurship',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurship',
            name='mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=7, null=True),
        ),
    ]
