# Generated by Django 5.2.1 on 2025-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0011_mediaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='url',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='event_subcategory',
            field=models.CharField(blank=True, choices=[("MoU's", "MoU's"), ('Officials', 'Officials'), ('Industrial Visit', 'Industrial Visit'), ('Naan Mudhalvan', 'Naan Mudhalvan'), ('Hackathon', 'Hackathon')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_items/'),
        ),
    ]
