# Generated by Django 5.2.1 on 2025-05-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0012_remove_mediaitem_url_mediaitem_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='event_subcategory',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='media_type',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='tansam_apl.mediacategory'),
        ),
    ]
