# Generated by Django 5.2.1 on 2025-05-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0013_mediacategory_remove_mediaitem_event_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediacategory',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='name',
            field=models.CharField(choices=[('Events', 'Events'), ('Print_Media', 'Print Media'), ('Linkedin', 'LinkedIn')], max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='MediaItem',
        ),
    ]
