# Generated by Django 5.2.1 on 2025-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0015_mediaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='event_images/')),
                ('category', models.CharField(choices=[('MoU', 'MoU'), ('Official', 'Official'), ('Industrial Visit', 'Industrial Visit'), ('Naan Mudhalvan', 'Naan Mudhalvan'), ('Hackathon', 'Hackathon')], max_length=50)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
