# Generated by Django 5.2.1 on 2025-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0016_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hackathon_description_style',
            field=models.CharField(blank=True, help_text='Font style for description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hackathon_fontawesome_icons',
            field=models.CharField(blank=True, help_text='FontAwesome icons HTML or class names', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hackathon_options',
            field=models.JSONField(blank=True, default=list, help_text='Multi-select options for Hackathon', null=True),
        ),
    ]
