# Generated by Django 5.2.1 on 2025-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0017_event_hackathon_description_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='hackathon_event_images/')),
                ('hackathon_options', models.JSONField(blank=True, default=list, help_text='Multi-select options for Hackathon', null=True)),
                ('hackathon_description_style', models.CharField(blank=True, help_text='Font style for description', max_length=100, null=True)),
                ('hackathon_fontawesome_icons', models.CharField(blank=True, help_text='FontAwesome icons HTML or class names', max_length=255, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='hackathon_description_style',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hackathon_fontawesome_icons',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hackathon_options',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('MoU', 'MoU'), ('Official', 'Official'), ('Industrial Visit', 'Industrial Visit'), ('Naan Mudhalvan', 'Naan Mudhalvan')], max_length=50),
        ),
    ]
