# Generated by Django 5.2.1 on 2025-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0018_hackathonevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonevent',
            name='hackathon_description_style',
        ),
        migrations.RemoveField(
            model_name='hackathonevent',
            name='hackathon_fontawesome_icons',
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='description_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='fontawesome_icons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonevent',
            name='hackathon_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonevent',
            name='image',
            field=models.ImageField(upload_to='hackathon_images/'),
        ),
    ]
