# Generated by Django 5.2.1 on 2025-05-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0019_remove_hackathonevent_hackathon_description_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonevent',
            name='description_style',
        ),
        migrations.RemoveField(
            model_name='hackathonevent',
            name='fontawesome_icons',
        ),
        migrations.RemoveField(
            model_name='hackathonevent',
            name='hackathon_options',
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='font_style',
            field=models.CharField(blank=True, choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Tahoma', 'Tahoma'), ('Trebuchet MS', 'Trebuchet MS'), ('Comic Sans MS', 'Comic Sans MS')], default='Arial', max_length=50, null=True),
        ),
    ]
