# Generated by Django 5.2.1 on 2025-06-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0025_alter_jobapplication_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('waiting', 'Waiting List')], default='applied', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('waiting', 'Waiting List')], max_length=20)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_entries', to='tansam_apl.jobapplication')),
            ],
        ),
    ]
