# Generated by Django 5.2.1 on 2025-06-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tansam_apl', '0026_alter_jobapplication_status_processedapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('waiting', 'Waiting')], max_length=20)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tansam_apl.job')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tansam_apl.jobapplication')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedApplication',
        ),
    ]
